name: Build & Push Docker (RunPod)

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'scripts/**'
      - 'bin/**'
      - 'manifests/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag additionnel (ex: v1.0.0)'
        required: false
        default: ''

env:
  IMAGE_REPO: docker.io/mauricebourdondock/runpod_comfy_ultime

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags (latest + stable + version)
        id: meta
        run: |
          SHA="${GITHUB_SHA::7}"
          RUN="v${GITHUB_RUN_NUMBER}"
          EXTRA="${{ github.event.inputs.tag }}"
          TAGS="${IMAGE_REPO}:runpod-amd64,${IMAGE_REPO}:latest,${IMAGE_REPO}:${RUN},${IMAGE_REPO}:${SHA}"
          if [ -n "$EXTRA" ]; then TAGS="${TAGS},${IMAGE_REPO}:${EXTRA}"; fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.IMAGE_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_REPO }}:buildcache,mode=max
